//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavigaMagazin.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertisingTable
    {
        public long id { get; set; }
        public string advertisingname { get; set; }
        public string advertisinglink { get; set; }
        public string advertisingphoto { get; set; }
        public Nullable<System.DateTime> advertisingstart { get; set; }
        public Nullable<System.DateTime> advertisingend { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string advertising260x230 { get; set; }
        public string advertising320x270 { get; set; }
        public string advertising320x540 { get; set; }
        public string advertising728x90banner { get; set; }
        public string advertising728x90 { get; set; }
        public Nullable<long> isaktif { get; set; }
        public string fixedad { get; set; }
        public Nullable<long> numberofclicks { get; set; }
        public Nullable<long> numberofview { get; set; }
    }
}
