//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavigaMagazin.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class calendarTable
    {
        public long id { get; set; }
        public string calendartitle { get; set; }
        public string calendercontent { get; set; }
        public string calenderlocation { get; set; }
        public Nullable<System.DateTime> creationtime { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> calendestartrdate { get; set; }
        public Nullable<System.DateTime> calenderenddate { get; set; }
    }
}
