//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavigaMagazin.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContentTable()
        {
            this.CommentTables = new HashSet<CommentTable>();
        }
    
        public long id { get; set; }
        public Nullable<long> categoryid { get; set; }
        public Nullable<long> userid { get; set; }
        public string posttitle { get; set; }
        public string postcontent { get; set; }
        public string postspottext { get; set; }
        public string postphoto { get; set; }
        public string url { get; set; }
        public Nullable<long> isaktif { get; set; }
        public Nullable<long> postview { get; set; }
        public Nullable<long> postlike { get; set; }
        public Nullable<long> postdislike { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public Nullable<System.DateTime> releasetime { get; set; }
        public string approved { get; set; }
        public string postshowroom { get; set; }
    
        public virtual CategoryTable CategoryTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentTable> CommentTables { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
