//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavigaMagazin.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualLog
    {
        public long id { get; set; }
        public string logexp { get; set; }
        public string whodidit { get; set; }
        public Nullable<System.DateTime> processingtime { get; set; }
    }
}
