//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavigaMagazin.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageTable
    {
        public long id { get; set; }
        public string messagefullname { get; set; }
        public string messageemail { get; set; }
        public string messagesubject { get; set; }
        public string messagedescription { get; set; }
        public Nullable<System.DateTime> messagetime { get; set; }
        public Nullable<int> messagestatu { get; set; }
    }
}
