//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavigaMagazin.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class navigaEntities : DbContext
    {
        public navigaEntities()
            : base("name=navigaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdvertisingTable> AdvertisingTables { get; set; }
        public virtual DbSet<calendarTable> calendarTables { get; set; }
        public virtual DbSet<CategoryTable> CategoryTables { get; set; }
        public virtual DbSet<CommentTable> CommentTables { get; set; }
        public virtual DbSet<ContentTable> ContentTables { get; set; }
        public virtual DbSet<EbultenTable> EbultenTables { get; set; }
        public virtual DbSet<magazineTable> magazineTables { get; set; }
        public virtual DbSet<ManualLog> ManualLogs { get; set; }
        public virtual DbSet<MenuTable> MenuTables { get; set; }
        public virtual DbSet<MessageTable> MessageTables { get; set; }
        public virtual DbSet<modalTable> modalTables { get; set; }
        public virtual DbSet<moonCalendar> moonCalendars { get; set; }
        public virtual DbSet<questionTable> questionTables { get; set; }
        public virtual DbSet<stormTable> stormTables { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UploadTable> UploadTables { get; set; }
        public virtual DbSet<UserRoleTable> UserRoleTables { get; set; }
        public virtual DbSet<UserTable> UserTables { get; set; }
        public virtual DbSet<videoTable> videoTables { get; set; }
    }
}
