//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavigaMagazin.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserTable()
        {
            this.CommentTables = new HashSet<CommentTable>();
            this.ContentTables = new HashSet<ContentTable>();
            this.questionTables = new HashSet<questionTable>();
            this.questionTables1 = new HashSet<questionTable>();
        }
    
        public long id { get; set; }
        public string username { get; set; }
        public string usersurname { get; set; }
        public string useremail { get; set; }
        public string userphoto { get; set; }
        public string userpassword { get; set; }
        public Nullable<long> userroleid { get; set; }
        public Nullable<long> isaktif { get; set; }
        public Nullable<System.DateTime> creationtime { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string userfacebook { get; set; }
        public string usertwitter { get; set; }
        public string useryoutube { get; set; }
        public string userlinkedin { get; set; }
        public string approved { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentTable> CommentTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentTable> ContentTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<questionTable> questionTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<questionTable> questionTables1 { get; set; }
        public virtual UserRoleTable UserRoleTable { get; set; }
    }
}
