//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavigaMagazin.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class videoTable
    {
        public long id { get; set; }
        public string videotitle { get; set; }
        public string videodescription { get; set; }
        public string videolink { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> releasetime { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public Nullable<int> isaktif { get; set; }
        public string showroom { get; set; }
    }
}
